# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['version']
  env: ['GOPATH=.']
  
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['GOPATH=.']

- name: 'gcr.io/cloud-builders/go'
  args: ['run', 'main']
  env: ['GOPATH=.']

# images:
# - 'gcr.io/$PROJECT_ID/golang-soma:latest'
